#!/usr/bin/env node
// Encrypts people.json -> data.enc.js so the plaintext never leaves this machine.
// Usage:  node build.mjs                          (prompts for the passphrase, not echoed)
//         ORG_PASSPHRASE='...' node build.mjs     (for scripting)
import { readFile, writeFile } from 'node:fs/promises';
import { webcrypto as crypto } from 'node:crypto';

const ITERATIONS = 250000;

function promptHidden(question) {
  return new Promise((resolve, reject) => {
    const { stdin, stdout } = process;
    if (!stdin.isTTY) return reject(new Error('No terminal available. Use ORG_PASSPHRASE=... node build.mjs'));
    stdout.write(question);
    stdin.setRawMode(true);
    stdin.resume();
    stdin.setEncoding('utf8');
    let value = '';
    const ETX = 3, BACKSPACE = 8, LF = 10, CR = 13, EOT = 4, DEL = 127;
    const onData = (char) => {
      const code = char.charCodeAt(0);
      if (code === CR || code === LF || code === EOT) {
        stdin.setRawMode(false);
        stdin.pause();
        stdin.removeListener('data', onData);
        stdout.write('\n');
        resolve(value);
      } else if (code === ETX) {
        stdin.setRawMode(false);
        stdout.write('\n');
        process.exit(130);
      } else if (code === DEL || code === BACKSPACE) {
        value = value.slice(0, -1);
      } else {
        value += char;
      }
    };
    stdin.on('data', onData);
  });
}

const b64 = (buf) => Buffer.from(buf).toString('base64');

const raw = await readFile(new URL('./people.json', import.meta.url), 'utf8');
let data;
try {
  data = JSON.parse(raw);
} catch (err) {
  console.error('people.json is not valid JSON: ' + err.message);
  process.exit(1);
}

// Validate before encrypting - a typo'd date is invisible once it is ciphertext.
const problems = [];
const families = data.families ?? [];
for (const family of families) {
  for (const m of family.members ?? []) {
    if (!m.name) problems.push(family.name + ': a member has no "name"');
    if (!m.birthdate) problems.push(family.name + ' / ' + m.name + ': no "birthdate"');
    else if (!/^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2})?$/.test(m.birthdate))
      problems.push(family.name + ' / ' + m.name + ': birthdate "' + m.birthdate + '" must be YYYY-MM-DD or YYYY-MM-DD HH:MM');
  }
}
if (problems.length) {
  console.error('Fix these first:\n  - ' + problems.join('\n  - '));
  process.exit(1);
}

const passphrase = process.env.ORG_PASSPHRASE ?? await promptHidden('Passphrase: ');
if (!passphrase) {
  console.error('No passphrase given.');
  process.exit(1);
}
if (passphrase.length < 6) {
  console.error('Use at least 6 characters.');
  process.exit(1);
}

const salt = crypto.getRandomValues(new Uint8Array(16));
const iv = crypto.getRandomValues(new Uint8Array(12));
const baseKey = await crypto.subtle.importKey('raw', new TextEncoder().encode(passphrase), 'PBKDF2', false, ['deriveKey']);
const key = await crypto.subtle.deriveKey(
  { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
  baseKey,
  { name: 'AES-GCM', length: 256 },
  false,
  ['encrypt']
);
const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, new TextEncoder().encode(JSON.stringify(data)));

const payload = { v: 1, it: ITERATIONS, salt: b64(salt), iv: b64(iv), ct: b64(ct) };
await writeFile(
  new URL('./data.enc.js', import.meta.url),
  '// Generated by build.mjs - AES-256-GCM, PBKDF2-SHA256. Do not edit by hand.\nwindow.__ORG_DATA__ = ' + JSON.stringify(payload) + ';\n'
);

const people = families.reduce((n, f) => n + (f.members?.length ?? 0), 0);
console.log('Encrypted ' + people + ' people across ' + families.length + ' departments -> data.enc.js');
