// Shared by build.mjs (CLI) and edit.mjs (editor's Publish button).
import { webcrypto as crypto } from 'node:crypto';

export const ITERATIONS = 250000;

const BIRTHDATE_RE = /^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2})?$/;

// A typo'd date is invisible once it is ciphertext, so check before encrypting.
export function validate(data) {
  const problems = [];
  if (!data || typeof data !== 'object') return ['The file is not a JSON object.'];
  const families = data.families ?? [];
  if (!Array.isArray(families)) return ['"families" must be a list.'];
  if (!families.length) problems.push('There are no departments yet.');
  for (const family of families) {
    const label = family.name || '(unnamed department)';
    if (!family.name) problems.push('A department has no name.');
    for (const m of family.members ?? []) {
      if (!m.name) problems.push(label + ': a member has no name.');
      if (!m.birthdate) problems.push(label + ' / ' + (m.name || '?') + ': no birthdate.');
      else if (!BIRTHDATE_RE.test(m.birthdate))
        problems.push(label + ' / ' + m.name + ': birthdate "' + m.birthdate + '" must be YYYY-MM-DD or YYYY-MM-DD HH:MM.');
    }
  }
  return problems;
}

export function countPeople(data) {
  return (data.families ?? []).reduce((n, f) => n + (f.members?.length ?? 0), 0);
}

export async function encryptToFileText(data, passphrase) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const baseKey = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(passphrase), 'PBKDF2', false, ['deriveKey']
  );
  const key = await crypto.subtle.deriveKey(
    { name: 'PBKDF2', salt, iterations: ITERATIONS, hash: 'SHA-256' },
    baseKey,
    { name: 'AES-GCM', length: 256 },
    false,
    ['encrypt']
  );
  const ct = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv }, key, new TextEncoder().encode(JSON.stringify(data))
  );
  const b64 = (buf) => Buffer.from(buf).toString('base64');
  const payload = { v: 1, it: ITERATIONS, salt: b64(salt), iv: b64(iv), ct: b64(ct) };
  return '// Generated by build.mjs - AES-256-GCM, PBKDF2-SHA256. Do not edit by hand.\n'
    + 'window.__ORG_DATA__ = ' + JSON.stringify(payload) + ';\n';
}
